### ISSUE TITLE
Any reason over functions instead of views?

### ISSUE THREAD

**Issue by josephtocci** [Tostino/pgAutomator#5]
@workflowproducts/dev
@Tostino

Some of the functions appear like they should be views.
For example:
pgautomator.create_step
pgautomator.edit_step
pgautomator.get_steps
pgautomator.remove_step

Appear to be CRUD for administrators, this could be easily accomplished in a view.
The advantage of a view is that table editors like in PGAdmin or Postage could edit the data in the view easily. With the functions you would need a specialized admin program. (Which you should have. But making it easier to administrator which simple tools is better all around.)

In order to create the view, you would need to:
SELECT:
Create view with left joins for all your tables.

INSERT:
Create rule on your table with multiple statements, one for each table.
or
Create a INSTEAD OF INSERT trigger on your view.
(Both are little used features of Postgres.)

UPDATE and INSERT can be done the same way on the view.

Then on any insert update or delete it will handle all the views.

I should note, we can work with how it is right now, it's just easier to handle CRUD with a view.

Was making CRUD functions a design decision? In other words, is there an advantage I'm missing?

Also, some of these table could be combined. Is there any reason to separate the tables, for example: pgautomator.step, pgautomator.step_connection and pgautomator.step_email?

**Comment by Tostino** [comment]
Hey @josephtocci, sorry very hectic week...  The main reason for sticking with functions over views for those simple use-cases is to stay consistent.  The other reason, is if there is a need to add logic for those couple which are just crud right now at a later point in time, that's easier to do.  I'd think that managing these jobs is complex enough that inserting the crud directly through a view or using a function directly is not something anyone will be doing unless they sufficiently understand the architecture, and in which case either are acceptable.


I kept those in separate tables just because of a separation of concerns.  There are plenty of jobs which will be setup without email being configured for them, so to make it easier to check if email was configured for them I split it into a separate table where I can just check on the job/step id for existence.  Not totally necessary, and it could for sure be merged into a single table.  I just thought it would make the architecture a little more clear.

**Comment by josephtocci** [comment]
>Hey @josephtocci, sorry very hectic week...

No problem, we've been busy with multiple projects lately so we know the feeling.

>The main reason for sticking with functions over views for those simple use-cases is to stay consistent.

As far as consistency with the API, the reason we wrote our first open source project is exactly because of this. Everyone's CRUD API for PostgreSQL only did CRUD, not functions. This among other reasons is why we wrote workflowproducts/envelope. With Envelope you can use views for editing data, and for business logic you use functions. Both have their purposes.

Aside:
We determined the whole CRUD only thing is pushed by people who use databases as a dumb store, and put business logic in a middle-ware like PHP or the web page.

### Theoretical situation:
The tables `pgautomator.job` and `pgautomator.job_email` are combined.
Select is just a select, no other tables are needed.
Insert and update are the same, nowhere else in the database needs anything changed as a result of a change in pgautomater.job.
Delete requires some other tables to have associated rows deleted. So one `BEFORE DELETE` trigger is added to the table.
The delete trigger is the only function you would need.

>The other reason, is if there is a need to add logic for those couple which are just crud right now at a later point in time, that's easier to do. I'd think that managing these jobs is complex enough that inserting the crud directly through a view or using a function directly is not something anyone will be doing unless they sufficiently understand the architecture, and in which case either are acceptable.

In order to update a single column somewhere, we would either have to do something like this:
````
DO LANGUAGE plpgsql
$$
DECLARE
    _job_id int;
    _job_category_id int;
    _job_name text;
    _job_description text;
    _job_enabled boolean;
    _job_timeout interval;
    _job_assigned_agent_id int;
    _email_on pgautomator.state;
    _email_to text;
    _email_subject text;
    _email_body text;

BEGIN
SELECT job.*, job_email.*
INTO _job_id, _job_category_id, _job_name, _job_description, _job_enabled, _job_timeout, _job_assigned_agent_id, _email_on, _email_to, _email_subject, _email_body
FROM pgautomator.job
LEFT JOIN pgautomator.job_email ON job.job_id = job_email.job_id
WHERE job.job_id = 5;

    _email_to := 'joseph@tocci.org';

    PERFORM pgautomator.edit_job(5, _job_category_id, _job_name, _job_description, _job_enabled, _job_timeout, _job_assigned_agent_id, _email_on, _email_to, _email_subject, _email_body);
END;
$$;
````
or the view/table way like this:
````
UPDATE pgautomator.job_email
    SET email_to = 'joseph@tocci.org'
WHERE job_id = 5;
````

I understand that people should just use the UI, but that doesn't mean make it hard for the UI developers. =)

>I kept those in separate tables just because of a separation of concerns. There are plenty of jobs which will be setup without email being configured for them, so to make it easier to check if email was configured for them I split it into a separate table where I can just check on the job/step id for existence.

Our standard practice for something like that would be keep it in one table, and if there is no TO address then ignore all the email columns. We only split into multiple tables if we run into the PostgreSQL column limit. (1600 columns if I remember correctly, happened once during an import. Long story.) Sometimes people will split like this so that they can have one table on one server and the other table on another server, but for a job scheduler we don't have that problem.

>Not totally necessary, and it could for sure be merged into a single table. I just thought it would make the architecture a little more clear.

If clarity is what you are worried about, start all the email columns with `email_` and add a comment to the TO column explain the circumstances for ignoring the email columns. (PostgreSQL and Postage both support column comments.)

Apologies for the long post.

>Test everything, retain what is good, reject what is useless, and add what is uniquely your own.
-Bruce Lee

If the way your are doing things is how you decide to do things, that's no problem. As Bruce Lee said, Test everything and retain what is good. So feel free to just takes the parts of this you like, or if you like nothing then take nothing. Let me know what your thoughts are on this.
